### ISSUE TITLE
New recaptcha (that does not need user input) on login + registration

### ISSUE THREAD

**Issue by P1llus** [Cysha/pxcms-auth#13]
I would like the possibility to enable registration and login recaptcha check, with the new Google recaptcha that just checks if you are a robot

https://www.google.com/recaptcha/intro/index.html

**Comment by xLink** [comment]
what are we thinking here? straight away have the recaptcha showing up, or only after x amount of attempts at register/logging in?

**Comment by P1llus** [comment]
Straight away on registration ofc and on login it would be great to be able
to set the limit or on first attempt in the admin panel.
20. jan. 2016 13:19 skrev "Dan Aldridge" <notifications@github.com>:

**Comment by xLink** [comment]
this is done in https://github.com/Cysha/pxcms-auth/commit/9f6afbc3a619e0c42a207afaa228b45b7d9cbaa6
