### ISSUE TITLE
Password Requirements page

### ISSUE THREAD

**Issue by Pillus** [Cysha/pxcms-auth#4]
Would be nice to be able for an admin to use the admin panel to set certain requirements for new users.
Requirements:
Password Length
Lower, Upper Case
If it needs special characters or not
Password age (with the possibility for infinite)

**Comment by xLink** [comment]
Added a toggle-able regex check for passwords, added basic functionality for password expiry

**Comment by xLink** [comment]
closing this as password expiry has been added as of PR https://github.com/Cysha/pxcms-auth/pull/17
